// SPDX-License-Identifier: GPL-3.0-only
pub mod app_page;
pub mod common;
pub mod creation;
pub mod dialogs;
pub mod icons;
pub mod library;
pub mod shell;
#[cfg(feature = "ui-tests")]
pub mod test_support;
